### ISSUE TITLE
Why is 2-bit quantization not supported by the kernel?

### ISSUE THREAD

**Issue by hmarkc** [SNU-ARC/any-precision-llm#4]
Thank you for your great work!

It seems that the current kernel only supports 3-8 bits. May I ask why 2-bit model is not supported by the kernel?

**Comment by ilil96** [comment]
We excluded 2-bit support because 2-bit precision results in a drastic degradation of model quality, which we consider impractical. However, if you need to support 2-bit precision, it can be implemented similarly to 3-bit precision.
