### ISSUE TITLE
Question regarding 2-bit quantization

### ISSUE THREAD

**Issue by jusjinuk** [SNU-ARC/any-precision-llm#6]
Hello,

Thank you for the amazing work and providing such a well-organized codebase.

I understand that 2-bit support is excluded from this codebase because of the significant degradation in performance (Issue #4), and I implemented 2-bit precision kernel on my own, thanks to the surprisingly intuitive implementation of the original code.

To verify my implementation, I compared the results with fake quantization results obtained with `fake_pack.py` (below snippet is part of the `results.json`)

```
    "anyprec-(Llama-2-7b-hf)-w8_orig2-gc1-c4_s100_blk512": {
        "ppl": {
            "2-bit:wikitext2": NaN,
            "2-bit:c4_new": 34.1552619934082,
            "2-bit:ptb_new_sliced": 38.83564376831055,
			...
        }
    },
    "fake_anyprec-p2-(Llama-2-7b-hf)-w8_orig2-gc1-c4_s100_blk512": {
        "ppl": {
            "None-bit:wikitext2": NaN,
            "None-bit:c4_new": 34.1552619934082,
            "None-bit:ptb_new_sliced": 38.83564376831055
        }
    },
```

You can find my implementation in the forked repo [here](https://github.com/jusjinuk/any-precision-llm). If there are any issues or missing details, I'd appreciate your feedback (it also fixes minor typo in README.md, please let me know if you want me to submit a pull-request).

You can reproduce the result by running `python quantize.py --seed_precision 2 meta-llama/Llama-2-7b-hf` in the forked repo.

My question is as follows:
- Do you have any insights on why the 2-bit wikitext2 perplexity here doesn't match the reported performance of SqueezeLLM for Llama-2-7b? Specifically, *Table F.10* of the [SqueezeLLM paper](https://arxiv.org/abs/2306.07629) shows that 2-bit perplexity for wikitext2 should be 35.49, yet the result here returns NaN. I used seed_precision as bits=2, which should correspond to SqueezeLLM's 2-bit performance.

I am aware that 2-bit quantization is beyond the scope of this codebase, but any insights into the cause of this discrepancy would be incredibly helpful for my research.

Thank you for your time.

**Comment by fwtan** [comment]
I'm not the maintainer of this repo but happen to work on this.

NaN could be fixed by: https://github.com/fwtan/any-precision-llm/blob/4a8e34c26716e995b9746b9a21cc971060f5e2f5/any_precision/modules/AnyPrecisionLinear.py#L72

SqueezeLLM used fp32 activations so there were lower chances to overflow. 

Here are the results of 2-bit llama 7b we got: [eval_results.json](https://github.com/user-attachments/files/16574125/eval_results.json)

**Comment by jusjinuk** [comment]
@fwtan Thank you so much for sharing your result. 

I double-checked that clipping indeed remedies the underflow/overflow. Closing the issue for now.

**Comment by jusjinuk** [comment]
Sharing the results before/after clipping for future people who might be interested in.

Before clipping:
```json
  "anyprec-(Llama-2-7b-hf)-w8_orig2-gc1-c4_s100_blk512": {
    "ppl": {
      "c4_new:2-bit": 34.1552619934082,
      "c4_new:3-bit": 8.325156211853027,
      "c4_new:4-bit": 7.459658145904541,
      "c4_new:5-bit": 7.3085784912109375,
      "c4_new:6-bit": 7.273617744445801,
      "c4_new:7-bit": 7.2652082443237305,
      "c4_new:8-bit": 7.263840675354004,
      "ptb_new_sliced:2-bit": 38.83564376831055,
      "ptb_new_sliced:3-bit": 9.229948997497559,
      "ptb_new_sliced:4-bit": 8.345032691955566,
      "ptb_new_sliced:5-bit": 8.16357421875,
      "ptb_new_sliced:6-bit": 8.121023178100586,
      "ptb_new_sliced:7-bit": 8.114277839660645,
      "ptb_new_sliced:8-bit": 8.107175827026367,
      "wikitext2:2-bit": NaN,
      "wikitext2:3-bit": 6.240961074829102,
      "wikitext2:4-bit": 5.644721508026123,
      "wikitext2:5-bit": 5.517499923706055,
      "wikitext2:6-bit": 5.483019828796387,
      "wikitext2:7-bit": 5.474261283874512,
      "wikitext2:8-bit": 5.472561836242676
    }
  },
```

After clipping:
```json
  "anyprec-(Llama-2-7b-hf)-w8_orig2-gc1-c4_s100_blk512": {
    "ppl": {
      "c4_new:2-bit": 34.1552619934082,
      "c4_new:3-bit": 8.325156211853027,
      "c4_new:4-bit": 7.459658145904541,
      "c4_new:5-bit": 7.3085784912109375,
      "c4_new:6-bit": 7.273617744445801,
      "c4_new:7-bit": 7.2652082443237305,
      "c4_new:8-bit": 7.263840675354004,
      "ptb_new_sliced:2-bit": 38.83564376831055,
      "ptb_new_sliced:3-bit": 9.229948997497559,
      "ptb_new_sliced:4-bit": 8.345032691955566,
      "ptb_new_sliced:5-bit": 8.16357421875,
      "ptb_new_sliced:6-bit": 8.121023178100586,
      "ptb_new_sliced:7-bit": 8.114277839660645,
      "ptb_new_sliced:8-bit": 8.107175827026367,
      "wikitext2:2-bit": 23.83866310119629,
      "wikitext2:3-bit": 6.240961074829102,
      "wikitext2:4-bit": 5.644721508026123,
      "wikitext2:5-bit": 5.517499923706055,
      "wikitext2:6-bit": 5.483019828796387,
      "wikitext2:7-bit": 5.474261283874512,
      "wikitext2:8-bit": 5.472561836242676
    }
  },
```

Seems like k-means clustering has bigger variance for 2-bit case. Increasing `max_iter` may be helpful.
